[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic-reflection = { workspace = true}
tonic = { workspace = true }
tokio = { workspace = true }

entity = { path = "../entity" }

eyre = { workspace = true }
